name: ZinPhotos
favicon: null
layout_spectrum: 0.73089
typography_spectrum: 0.46466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8499544514343143
  lightness: 0.21810611430555582
  saturation: 0.46632139780558646
  rhythmicContrast: 0.9177417505998164
purpose: []
